output_dir: /home/sles/torchtune/gemma2_2B/lora_single_device

# Tokenizer
tokenizer:
  _component_: torchtune.models.gemma.gemma_tokenizer
  path: /home/sles/gemma-2-2b-it/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  source: kraih/legaldb-training
  packed: False
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.gemma2.lora_gemma2_2b
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.0

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/sles/gemma-2-2b-it/
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: GEMMA2
resume_from_checkpoint: False
save_adapter_weights_only: False

optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 2e-5

lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 10

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Fine-tuning arguments
batch_size: 4
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 8
clip_grad_norm: null
compile: True

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
enable_activation_offloading: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True

# Profiler
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False
  output_dir: ${output_dir}/profiling_outputs
  cpu: True
  cuda: True
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False
  wait_steps: 5
  warmup_steps: 5
  active_steps: 2
  num_cycles: 1
