output_dir: /home/slesi/torchtune/qwen2_5_1_5B/lora_single_device

# Model arguments
model:
  _component_: torchtune.models.qwen2_5.lora_qwen2_5_1_5b_instruct
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: True
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.0

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /home/sles/Qwen2.5-1.5B-Instruct/vocab.json
  merges_file: /home/sles/Qwen2.5-1.5B-Instruct/merges.txt
  max_seq_len: null

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/sles/Qwen2.5-1.5B-Instruct
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
resume_from_checkpoint: False

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
  source: kraih/legaldb-training
  packed: False
seed: null
shuffle: True

# Fine-tuning arguments
epochs: 1
max_steps_per_epoch: null
batch_size: 8
gradient_accumulation_steps: 8
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training env
device: cuda

# Memory management / performance
enable_activation_checkpointing: True
enable_activation_offloading: True
dtype: bf16
clip_grad_norm: null
compile: True

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False
  output_dir: ${output_dir}/profiling_outputs
  cpu: True
  cuda: True
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
